apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: robomart
  labels:
    name: nginx
    environment: dev 
    project: robomart
spec:
  containers: 
  - name: nginx
    image: nginx:1.29.3-alpine
    ports:
    - containerPort: 80
