apiVersion: v1 
kind: Pod 
metadata:
  name: multi-container
  labels:
    purpose: multi-container
spec:
  containers:
  #container 1
  - name: nginx
    image: nginx:1.29.3-alpine
    ports:
    - containerPort: 80
  #container 2
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "1000"]