apiVersion: v1 
kind: Pod 
metadata:
  name: demo-resources
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
        #Minimum guaranteed resources
          memory: "60Mi"
          cpu: "100m"
        limits:
        #Maximum allowed resources
          memory: "100Mi"
          cpu: "120m"

