apiVersion: v1
kind: Service
metadata:
  name: frontend-np
spec:
  type: NodePort
  selector: 
    project: robomart
    component: frontend
    envionment: dev
    purpose: nodeport
  ports:
   - protocol: TCP
     port: 80 #service port
     targetPort: 80 #container port