apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
spec:
  type: LoadBalancer
  selector: 
    project: robomart
    component: frontend
    envionment: dev
    purpose: loadbalancer
  ports:
   - protocol: TCP
     port: 80 #service port
     targetPort: 80 #container port
     nodePort: 30009 #nodeport 