apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-demo
  labels:
    project: robomart
    component: frontend
    envionment: dev
    purpose: loadbalancer
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx

  