apiVersion: v1
kind: ReplicaSet
metadata:
  name: replicaset-demo
  labels:
    project: robomart
    environment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx

  