apiVersion: apps/v1
kind: Deployment 
metadata:
  name: frontend-dp
# these are replica set labels
  labels:
    purpose: dp-demo
    project: robomart
spec:
  replicas: 2
  selector: 
# these labels are used to select pods
    matchLabels:
      purpose: dp-demo
      project: robomart
  template:
    metadata:
      labels:
        purpose: dp-demo
        project: robomart
    spec:
      containers:
      - name: nginx
        image: nginx:1.29.3-alpine
